// examples/kitchen-sink-vue/src/App.vue
<script setup lang="ts">
import {useTemplateRef, onMounted} from 'vue'
import {createEffect} from 'solid-js'
import './KitchenSink.js'
import './Foo.ce.js'

const sink = useTemplateRef('sink')
const sink2 = useTemplateRef('sink2')

onMounted(() => {
	createEffect(() => {
		console.log('values outside the element:', sink.value!.count, sink.value!.name, sink.value!.doingSomething)
	})

	// Event listeners can be set on 'on*' event properties directly, as
	// with builtin events, as an alternative to `.addEventListener()`.
	sink2.value!.onawesomeness = event => {
		console.log('more awesomeness happened!', event.type)
	}
})
</script>

<template>
	<!-- Start with an initial value of 5 -->
	<kitchen-sink
		ref="sink"
		id="sink"
		count="5"
		name="Mo"
		doingSomething
		@click="
			() => {
				sink!.count++
				sink!.name += 'Mo'
				// Get or set attributes (dash-case)
				sink!.setAttribute(
					'doing-something',
					// Or get or set the same-name properties (camelCase)
					sink!.doingSomething ? 'false' : 'true',
				)
				console.log('doingSomething after attribute change:', sink!.doingSomething)
			}
		"
		@awesomeness="
			event => {
				console.log('awesomeness happened!', event.type)
			}
		"
		onawesomeness="console.log('this works too!')"
	></kitchen-sink>

	<kitchen-sink
		ref="sink2"
		id="sink2"
		count="1"
		name="Po"
		doingSomething="false"
		color="blue"
		@awesomeness="console.log('And this also works!')"
	>
		<p>child from light DOM, no slot specified</p>
		<p slot="foo">child from light DOM, slotted to the foo slot</p>
	</kitchen-sink>
</template>

<style scoped>
kitchen-sink#sink {
	cursor: pointer;
	user-select: none;
}
</style>

// examples/kitchen-sink-angular/src/app/app.component.ts
import {Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, ViewChild, viewChild} from '@angular/core'
import {RouterOutlet} from '@angular/router'
import '../KitchenSink.js'
import {KitchenSink} from '../KitchenSink.js'
import {createEffect} from 'solid-js'

@Component({
	selector: 'app-root',
	standalone: true,
	imports: [RouterOutlet],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	templateUrl: './app.component.html',
	styleUrl: './app.component.css',
})
export class AppComponent {
	title = 'kitch-sink-angular'

	@ViewChild('sink') sink!: ElementRef<KitchenSink>
	@ViewChild('sink2') sink2!: ElementRef<KitchenSink>

	ngAfterViewInit() {
		const sink = this.sink.nativeElement

		createEffect(() => {
			console.log('values outside the element:', sink.count, sink.name, sink.doingSomething)
		})

		const sink2 = this.sink2.nativeElement

		// Event listeners can be set on 'on*' event properties directly, as with builtin events.
		sink2.onawesomeness = event => {
			console.log('more awesomeness happened!', event.type)
		}
	}

	clickSink1(event: Event) {
		const sink = this.sink.nativeElement
		sink.count++
		sink.name += 'Mo'
		// Get or set attributes (dash-case)
		sink.setAttribute(
			'doing-something',
			// Or get or set the same-name properties (camelCase)
			sink.doingSomething ? 'false' : 'true',
		)
		console.log('doingSomething after attribute change:', sink.doingSomething)
	}

	onSink1Awesomeness(event: Event) {
		console.log('awesomeness happened!', event.type)
	}
}

<!-- Start with an initial value of 5 -->
<kitchen-sink
	#sink
	id="sink"
	[attr.count]="'5'"
	[name]="'Mo'"
	doing-something
	(click)="clickSink1($event)"
	(awesomeness)="onSink1Awesomeness($event)"
	onawesomeness="console.log('this works too!', event.type)"
></kitchen-sink>

<kitchen-sink #sink2 id="sink2" count="1" name="Po" doing-something="false" color="blue">
	<p>child from light DOM, no slot specified</p>
	<p slot="foo">child from light DOM, slotted to the foo slot</p>
</kitchen-sink>

<router-outlet />
